/**
 * SYNTHETIC DEMONSTRATION DATA GENERATOR
 * Project: Dynamic Human-Robot Safety-Zone Simulator for Process Plants
 * 
 * DISCLAIMER:
 * All records generated by this script are SYNTHETIC DEMONSTRATION SAMPLES
 * created mathematically for research prototype algorithm validation.
 * They DO NOT represent real-world certified industrial plant measurements.
 * 
 * Usage:
 *   npx tsx scripts/generateSyntheticData.ts
 *   or via node with TypeScript execution tooling.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface SyntheticSample {
  timestamp: string;
  sample_type: 'SYNTHETIC_BENCHMARK' | 'SYNTHETIC_EDGE_CASE';
  scenario: string;
  robot_id: string;
  human_role: string;
  robot_x: number;
  robot_y: number;
  human_x: number;
  human_y: number;
  robot_speed: number;
  human_speed: number;
  reaction_time: number;
  stopping_time: number;
  base_distance: number;
  safety_margin: number;
  task_type: string;
  task_factor: number;
  direction_factor: number;
  separation_distance: number;
  required_dynamic_distance: number;
  static_baseline_distance: number;
  risk_state: 'SAFE' | 'WARNING' | 'UNSAFE' | 'EMERGENCY';
  unnecessary_restriction_flag: boolean;
}

// Pseudo-random deterministic linear congruential generator (LCG)
class SeededRNG {
  private seed: number;
  constructor(seed: number = 42) {
    this.seed = seed;
  }
  next(): number {
    this.seed = (this.seed * 9301 + 49297) % 233280;
    return this.seed / 233280;
  }
}

export function generateSyntheticDataset(seed: number = 2026): SyntheticSample[] {
  const rng = new SeededRNG(seed);
  const dataset: SyntheticSample[] = [];

  const taskFactors: Record<string, number> = {
    'Inspection': 1.0,
    'Maintenance': 1.4,
    'Material handling': 1.3,
    'Quality checking': 1.1,
    'Equipment monitoring': 1.0,
    'Cleaning': 1.2,
  };

  const scenarios = [
    { name: 'Scenario 1: Normal Operation (Parallel Paths)', robotSpeed: 1.2, humanSpeed: 1.1, task: 'Inspection', count: 40 },
    { name: 'Scenario 2: Converging Crossway', robotSpeed: 1.4, humanSpeed: 1.3, task: 'Material handling', count: 50 },
    { name: 'Scenario 3: High-Speed AMR Valve Service', robotSpeed: 2.4, humanSpeed: 0.5, task: 'Maintenance', count: 40 },
    { name: 'Edge Case: Coincident Initial Position', robotSpeed: 0.0, humanSpeed: 0.0, task: 'Inspection', count: 5, forceEmergency: true },
    { name: 'Edge Case: Stationary Robot Baseline', robotSpeed: 0.0, humanSpeed: 1.2, task: 'Inspection', count: 10, stationary: true },
    { name: 'Edge Case: Velocity Limit Anomaly', robotSpeed: 9.5, humanSpeed: 1.0, task: 'Material handling', count: 5, excessiveSpeed: true },
  ];

  let recordCounter = 1;
  const baseTime = new Date('2026-09-06T08:00:00Z').getTime();

  for (const sc of scenarios) {
    for (let i = 0; i < sc.count; i++) {
      const stepTime = new Date(baseTime + recordCounter * 1000).toISOString();
      recordCounter++;

      let rx = 30 + (i * 0.8);
      let ry = 40 + Math.sin(i * 0.2) * 5;
      let hx = 30 + (i * 0.8);
      let hy = 80;

      if (sc.name.includes('Converging')) {
        rx = 50;
        ry = 30 + (i * 0.8);
        hx = 80 - (i * 0.9);
        hy = 50;
      } else if (sc.forceEmergency) {
        rx = 50;
        ry = 50;
        hx = 50;
        hy = 50;
      } else if (sc.stationary) {
        rx = 50;
        ry = 50;
        hx = 30 + (i * 1.2);
        hy = 56;
      }

      const dx = hx - rx;
      const dy = hy - ry;
      const separation = Math.round(Math.sqrt(dx * dx + dy * dy) * 100) / 100;

      const rSpeed = sc.robotSpeed;
      const hSpeed = sc.humanSpeed;
      const tStop = sc.excessiveSpeed ? 3.5 : 0.6;
      const tReact = 0.7;
      const baseDist = 1.2;
      const margin = 0.8;
      const taskF = taskFactors[sc.task] || 1.0;
      const dirF = sc.name.includes('Converging') ? 1.25 : 1.0;

      const reqDist = Math.round(((baseDist + (rSpeed * tStop * 1.2) + (hSpeed * tReact * 1.0) + (0.5 * tReact * 1.1)) * taskF * dirF + margin) * 100) / 100;
      const staticBaseline = 4.5;

      let riskState: SyntheticSample['risk_state'] = 'SAFE';
      if (separation <= 1.0 || (rx === hx && ry === hy)) {
        riskState = 'EMERGENCY';
      } else if (separation < reqDist) {
        riskState = 'UNSAFE';
      } else if (separation < reqDist + 1.2) {
        riskState = 'WARNING';
      }

      const baselineBreached = separation < staticBaseline;
      const unnecessaryRestriction = baselineBreached && riskState === 'SAFE';

      dataset.push({
        timestamp: stepTime,
        sample_type: sc.name.includes('Edge') ? 'SYNTHETIC_EDGE_CASE' : 'SYNTHETIC_BENCHMARK',
        scenario: sc.name,
        robot_id: 'SYNTH-AMR-01',
        human_role: 'Plant Technician',
        robot_x: Math.round(rx * 100) / 100,
        robot_y: Math.round(ry * 100) / 100,
        human_x: Math.round(hx * 100) / 100,
        human_y: Math.round(hy * 100) / 100,
        robot_speed: rSpeed,
        human_speed: hSpeed,
        reaction_time: tReact,
        stopping_time: tStop,
        base_distance: baseDist,
        safety_margin: margin,
        task_type: sc.task,
        task_factor: taskF,
        direction_factor: dirF,
        separation_distance: separation,
        required_dynamic_distance: reqDist,
        static_baseline_distance: staticBaseline,
        risk_state: riskState,
        unnecessary_restriction_flag: unnecessaryRestriction,
      });
    }
  }

  return dataset;
}

// Convert dataset to CSV
export function datasetToCSV(samples: SyntheticSample[]): string {
  const headers = [
    'timestamp',
    'sample_type',
    'scenario',
    'robot_id',
    'human_role',
    'robot_x',
    'robot_y',
    'human_x',
    'human_y',
    'robot_speed',
    'human_speed',
    'reaction_time',
    'stopping_time',
    'base_distance',
    'safety_margin',
    'task_type',
    'task_factor',
    'direction_factor',
    'separation_distance',
    'required_dynamic_distance',
    'static_baseline_distance',
    'risk_state',
    'unnecessary_restriction_flag',
  ];

  const rows = samples.map((s) => [
    `"${s.timestamp}"`,
    `"${s.sample_type}"`,
    `"${s.scenario}"`,
    `"${s.robot_id}"`,
    `"${s.human_role}"`,
    s.robot_x,
    s.robot_y,
    s.human_x,
    s.human_y,
    s.robot_speed,
    s.human_speed,
    s.reaction_time,
    s.stopping_time,
    s.base_distance,
    s.safety_margin,
    `"${s.task_type}"`,
    s.task_factor,
    s.direction_factor,
    s.separation_distance,
    s.required_dynamic_distance,
    s.static_baseline_distance,
    `"${s.risk_state}"`,
    s.unnecessary_restriction_flag,
  ]);

  return [
    '# SYNTHETIC DEMONSTRATION DATASET - NOT REAL INDUSTRIAL MEASUREMENTS',
    headers.join(','),
    ...rows.map((r) => r.join(',')),
  ].join('\n');
}

// Standalone execution runner
function run() {
  const dataset = generateSyntheticDataset(2026);
  const csvContent = datasetToCSV(dataset);
  const outDir = path.resolve(process.cwd(), 'docs');
  
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const csvPath = path.join(outDir, 'synthetic_safety_dataset.csv');
  const jsonPath = path.join(outDir, 'synthetic_safety_dataset.json');

  fs.writeFileSync(csvPath, csvContent, 'utf-8');
  fs.writeFileSync(jsonPath, JSON.stringify(dataset, null, 2), 'utf-8');

  console.log(`[SYNTHETIC GENERATOR] Successfully created ${dataset.length} synthetic records.`);
  console.log(`[SYNTHETIC GENERATOR] Exported CSV: ${csvPath}`);
  console.log(`[SYNTHETIC GENERATOR] Exported JSON: ${jsonPath}`);
}

// Auto-run if executed directly
if (typeof process !== 'undefined' && process.argv && process.argv[1] && process.argv[1].includes('generateSyntheticData')) {
  run();
}
