/**
 * SYNTHETIC DEMONSTRATION DATA GENERATOR (Review 2 Extended)
 * Project: Dynamic Human-Robot Safety-Zone Simulator for Process Plants
 * 
 * DISCLAIMER:
 * All records generated by this script are SYNTHETIC DEMONSTRATION SAMPLES
 * created mathematically for research prototype algorithm validation.
 * They DO NOT represent real-world certified industrial plant measurements.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface SyntheticSample {
  timestamp: string;
  sample_type: 'SYNTHETIC_BENCHMARK' | 'SYNTHETIC_EDGE_CASE';
  scenario: string;
  robot_id: string;
  human_role: string;
  robot_x: number;
  robot_y: number;
  human_x: number;
  human_y: number;
  robot_speed: number;
  human_speed: number;
  reaction_time: number;
  stopping_time: number;
  base_distance: number;
  safety_margin: number;
  friction_coefficient: number;
  temperature_celsius: number;
  sensor_degradation_factor: number;
  task_type: string;
  task_factor: number;
  direction_factor: number;
  separation_distance: number;
  required_dynamic_distance: number;
  static_baseline_distance: number;
  risk_state: 'SAFE' | 'WARNING' | 'UNSAFE' | 'EMERGENCY';
  unnecessary_restriction_flag: boolean;
}

class SeededRNG {
  private seed: number;
  constructor(seed: number = 2026) {
    this.seed = seed;
  }
  next(): number {
    this.seed = (this.seed * 9301 + 49297) % 233280;
    return this.seed / 233280;
  }
}

export function generateSyntheticDataset(seed: number = 2026): SyntheticSample[] {
  const rng = new SeededRNG(seed);
  const dataset: SyntheticSample[] = [];

  const scenarios = [
    { name: 'Scenario 1: Head-On Process Walkway', friction: 1.0, temp: 25, sensorDeg: 0.0, baseDir: 1.5 },
    { name: 'Scenario 2: Perpendicular Blind Corner', friction: 1.0, temp: 25, sensorDeg: 0.0, baseDir: 1.2 },
    { name: 'Scenario 3: High-Speed Overtaking Corridor', friction: 1.0, temp: 25, sensorDeg: 0.0, baseDir: 0.8 },
    { name: 'Scenario 4: Multi-Agent Convergence (2 AMRs + 2 Humans)', friction: 1.0, temp: 28, sensorDeg: 0.05, baseDir: 1.4 },
    { name: 'Scenario 5: Chemical Washdown Wet Corridor (μ=0.65)', friction: 0.65, temp: 32, sensorDeg: 0.15, baseDir: 1.3 },
    { name: 'Scenario 6: Cold Storage Frost Slick (μ=0.20)', friction: 0.20, temp: -15, sensorDeg: 0.25, baseDir: 1.2 }
  ];

  const edgeCases = [
    'EC-01: Zero Speed Stationary Proximity',
    'EC-02: Maximum Velocity Extreme Approach',
    'EC-03: Ultra High Reaction Time Latency',
    'EC-04: High Risk Inspection Area Tight Clearance',
    'EC-05: Co-linear Opposite Trajectory Head-On',
    'EC-06: Zero Buffer Boundary Tolerance',
    'EC-07: Zero Friction Extreme Loss of Traction (μ=0.05)',
    'EC-08: Optical Sensor Complete Blindness (η=0.90)',
    'EC-09: Coincident Coordinates Singularity (Separation=0.0m)',
    'EC-10: Multi-AMR Fleet Head-On Deadlock Collision',
    'EC-11: Extreme Ambient Thermal Stress (+60°C Boiler)',
    'EC-12: High-Density Walkway Multi-Agent Clutter'
  ];

  // 1. Generate Scenario Benchmarks (120 samples per scenario = 720 samples)
  scenarios.forEach((sc, scIdx) => {
    for (let i = 0; i < 120; i++) {
      const stepTime = i * 0.2;
      const rSpeed = Number((0.8 + rng.next() * 1.6).toFixed(2));
      const hSpeed = Number((0.4 + rng.next() * 1.2).toFixed(2));
      const rX = Number((10 + (i * 0.5) + (rng.next() * 2)).toFixed(2));
      const rY = Number((20 + (rng.next() * 5)).toFixed(2));
      const hX = Number((80 - (i * 0.4) + (rng.next() * 2)).toFixed(2));
      const hY = Number((22 + (rng.next() * 4)).toFixed(2));
      const sepDist = Number(Math.hypot(hX - rX, hY - rY).toFixed(2));

      const stoppingTime = 0.8;
      const reactionTime = 0.5;
      const baseDist = 1.0;
      const safetyMargin = 0.5;

      const robotStoppingDist = (rSpeed * stoppingTime * 1.0) / Math.max(0.1, sc.friction);
      const robotReactionDist = rSpeed * 0.1;
      const humanIntrusionDist = hSpeed * reactionTime * 1.0;
      const ambientFactor = 1.0 + ((sc.temp - 25) * 0.005);
      const nominalBuffer = baseDist * ambientFactor;
      const sensorBuffer = sc.sensorDeg * 1.5;

      const dynamicReq = Number(((robotReactionDist + robotStoppingDist + humanIntrusionDist) * sc.baseDir + nominalBuffer + sensorBuffer + safetyMargin).toFixed(2));
      const staticReq = 3.0;

      let riskState: 'SAFE' | 'WARNING' | 'UNSAFE' | 'EMERGENCY' = 'SAFE';
      if (sepDist <= dynamicReq * 0.35) riskState = 'EMERGENCY';
      else if (sepDist <= dynamicReq * 0.65) riskState = 'UNSAFE';
      else if (sepDist <= dynamicReq) riskState = 'WARNING';

      const unnecessaryRestriction = sepDist >= dynamicReq && sepDist < staticReq;

      dataset.push({
        timestamp: `2026-10-01T10:${String(scIdx).padStart(2, '0')}:${String(Math.floor(stepTime)).padStart(2, '0')}.000Z`,
        sample_type: 'SYNTHETIC_BENCHMARK',
        scenario: sc.name,
        robot_id: scIdx === 3 ? (i % 2 === 0 ? 'AMR-01' : 'AMR-02') : 'AMR-01',
        human_role: scIdx === 3 ? (i % 2 === 0 ? 'Process Operator' : 'Maintenance Tech') : 'Process Operator',
        robot_x: rX,
        robot_y: rY,
        human_x: hX,
        human_y: hY,
        robot_speed: rSpeed,
        human_speed: hSpeed,
        reaction_time: reactionTime,
        stopping_time: stoppingTime,
        base_distance: baseDist,
        safety_margin: safetyMargin,
        friction_coefficient: sc.friction,
        temperature_celsius: sc.temp,
        sensor_degradation_factor: sc.sensorDeg,
        task_type: 'MATERIAL_TRANSPORT',
        task_factor: 1.0,
        direction_factor: sc.baseDir,
        separation_distance: sepDist,
        required_dynamic_distance: dynamicReq,
        static_baseline_distance: staticReq,
        risk_state: riskState,
        unnecessary_restriction_flag: unnecessaryRestriction
      });
    }
  });

  // 2. Generate Edge Case Samples (25 samples per edge case = 300 samples)
  edgeCases.forEach((ecName, ecIdx) => {
    for (let j = 0; j < 25; j++) {
      let rSpeed = 1.5;
      let hSpeed = 1.0;
      let sepDist = 2.5;
      let friction = 1.0;
      let sensorDeg = 0.0;
      let temp = 25;
      let riskState: 'SAFE' | 'WARNING' | 'UNSAFE' | 'EMERGENCY' = 'SAFE';

      if (ecIdx === 0) { rSpeed = 0.0; hSpeed = 0.0; sepDist = 1.2; riskState = 'SAFE'; }
      else if (ecIdx === 1) { rSpeed = 3.5; hSpeed = 2.5; sepDist = 1.5; riskState = 'EMERGENCY'; }
      else if (ecIdx === 2) { sepDist = 2.0; riskState = 'UNSAFE'; }
      else if (ecIdx === 3) { sepDist = 1.8; riskState = 'WARNING'; }
      else if (ecIdx === 4) { sepDist = 0.8; riskState = 'EMERGENCY'; }
      else if (ecIdx === 5) { sepDist = 0.5; riskState = 'EMERGENCY'; }
      else if (ecIdx === 6) { friction = 0.05; sepDist = 3.5; riskState = 'EMERGENCY'; }
      else if (ecIdx === 7) { sensorDeg = 0.90; sepDist = 2.2; riskState = 'UNSAFE'; }
      else if (ecIdx === 8) { sepDist = 0.0; riskState = 'EMERGENCY'; }
      else if (ecIdx === 9) { sepDist = 0.4; riskState = 'EMERGENCY'; }
      else if (ecIdx === 10) { temp = 60; sepDist = 2.0; riskState = 'WARNING'; }
      else if (ecIdx === 11) { sepDist = 1.1; riskState = 'UNSAFE'; }

      const dynamicReq = Number((((rSpeed * 0.8 / Math.max(0.05, friction)) + (hSpeed * 0.5)) + 1.5 + (sensorDeg * 1.5)).toFixed(2));

      dataset.push({
        timestamp: `2026-10-01T11:${String(ecIdx).padStart(2, '0')}:${String(j).padStart(2, '0')}.000Z`,
        sample_type: 'SYNTHETIC_EDGE_CASE',
        scenario: ecName,
        robot_id: 'AMR-01',
        human_role: 'Safety Verification Rig',
        robot_x: Number((20 + (rng.next() * 5)).toFixed(2)),
        robot_y: Number((20 + (rng.next() * 5)).toFixed(2)),
        human_x: Number((20 + (rng.next() * 5)).toFixed(2)),
        human_y: Number((20 + (rng.next() * 5)).toFixed(2)),
        robot_speed: rSpeed,
        human_speed: hSpeed,
        reaction_time: 0.5,
        stopping_time: 0.8,
        base_distance: 1.0,
        safety_margin: 0.5,
        friction_coefficient: friction,
        temperature_celsius: temp,
        sensor_degradation_factor: sensorDeg,
        task_type: 'EDGE_CASE_TEST',
        task_factor: 1.2,
        direction_factor: 1.5,
        separation_distance: sepDist,
        required_dynamic_distance: dynamicReq,
        static_baseline_distance: 3.0,
        risk_state: riskState,
        unnecessary_restriction_flag: false
      });
    }
  });

  return dataset;
}

// Generate files if executed directly
const dataset = generateSyntheticDataset(2026);
const docsDir = path.resolve(process.cwd(), 'docs');
if (!fs.existsSync(docsDir)) {
  fs.mkdirSync(docsDir, { recursive: true });
}

// Write JSON
const jsonPath = path.join(docsDir, 'synthetic_safety_dataset.json');
fs.writeFileSync(jsonPath, JSON.stringify(dataset, null, 2), 'utf8');

// Write CSV
const csvPath = path.join(docsDir, 'synthetic_safety_dataset.csv');
const headers = Object.keys(dataset[0]).join(',');
const rows = dataset.map(row => Object.values(row).join(','));
fs.writeFileSync(csvPath, [headers, ...rows].join('\n'), 'utf8');

console.log(`Successfully generated ${dataset.length} synthetic demonstration samples.`);
console.log(`JSON written to: ${jsonPath}`);
console.log(`CSV written to: ${csvPath}`);
