import type { ScenarioDefinition, PlantLayout } from '../../types';
import { DEFAULT_SAFETY_RULES } from '../safety/safetyEngine';

export const DEFAULT_PLANT_LAYOUT: PlantLayout = {
  id: 'layout-process-plant-01',
  name: 'Heavy Chemical Process Plant - Unit 4B',
  width: 100, // 100 meters
  height: 100, // 100 meters
  gridSize: 5,
  objects: [
    {
      id: 'eq-1',
      name: 'Fractionation Column A',
      type: 'equipment',
      x: 15,
      y: 15,
      width: 18,
      height: 14,
      color: '#3b82f6',
      description: 'Primary distillation and fractionation unit',
    },
    {
      id: 'eq-2',
      name: 'High Pressure Reactor 02',
      type: 'equipment',
      x: 65,
      y: 15,
      width: 20,
      height: 16,
      color: '#06b6d4',
      description: 'Catalytic continuous chemical reactor',
    },
    {
      id: 'eq-3',
      name: 'Compressor Skid & Pumps',
      type: 'equipment',
      x: 15,
      y: 65,
      width: 22,
      height: 15,
      color: '#6366f1',
      description: 'Feed gas compression and hydraulic pumps',
    },
    {
      id: 'rs-1',
      name: 'Robotic Valve Actuation Station',
      type: 'robot_station',
      x: 50,
      y: 45,
      width: 12,
      height: 12,
      color: '#f59e0b',
      description: 'Autonomous mobile robot (AMR) docking & payload station',
    },
    {
      id: 'ws-1',
      name: 'Technician Inspection Bay',
      type: 'workstation',
      x: 75,
      y: 70,
      width: 14,
      height: 12,
      color: '#10b981',
      description: 'Manual sample extraction and quality station',
    },
    {
      id: 'rz-1',
      name: 'High Voltage / Flammable Zone',
      type: 'restricted_zone',
      x: 40,
      y: 10,
      width: 18,
      height: 12,
      color: '#ef4444',
      restrictedReason: 'Explosive atmosphere hazard (ATEX Zone 1)',
    },
  ],
};

export const PREDEFINED_SCENARIOS: ScenarioDefinition[] = [
  {
    id: 'sc-1-normal',
    name: 'Scenario 1: Normal Operation (Parallel Safe Routes)',
    description: 'Autonomous inspection AMR and Plant Technician operate simultaneously on isolated parallel pathways with ample clearance. Dynamic safety system prevents false alarms.',
    expectedOutcome: 'SAFE',
    duration: 30,
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'KUKA KMP-1500 AMR',
      type: 'Heavy Industrial AGV',
      position: { x: 30, y: 40 },
      currentSpeed: 1.2,
      maxSpeed: 2.5,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.6,
      baseRadius: 1.0,
      currentWaypointIndex: 0,
      path: [
        { x: 30, y: 40 },
        { x: 60, y: 40 },
        { x: 60, y: 55 },
        { x: 30, y: 55 },
      ],
    },
    initialHuman: {
      id: 'worker-01',
      name: 'John Doe (Safety Lead)',
      position: { x: 30, y: 80 },
      currentSpeed: 1.1,
      expectedSpeed: 1.2,
      direction: 0,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.7,
      currentWaypointIndex: 0,
      path: [
        { x: 30, y: 80 },
        { x: 65, y: 80 },
        { x: 65, y: 90 },
        { x: 30, y: 90 },
      ],
    },
  },
  {
    id: 'sc-2-approach',
    name: 'Scenario 2: Human Approaches Robot (Converging Path)',
    description: 'Technician walks across the AMR delivery aisle to reach the valve manifold. Dynamic zone triggers WARNING as separation decreases, transitioning to UNSAFE when safety envelope is breached.',
    expectedOutcome: 'UNSAFE',
    duration: 25,
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'KUKA KMP-1500 AMR',
      type: 'Heavy Industrial AGV',
      position: { x: 50, y: 30 },
      currentSpeed: 1.4,
      maxSpeed: 2.5,
      direction: Math.PI / 2,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 1.0,
      currentWaypointIndex: 0,
      path: [
        { x: 50, y: 30 },
        { x: 50, y: 70 },
        { x: 50, y: 30 },
      ],
    },
    initialHuman: {
      id: 'worker-02',
      name: 'Sarah Connor (Technician)',
      position: { x: 80, y: 50 },
      currentSpeed: 1.3,
      expectedSpeed: 1.3,
      direction: Math.PI,
      task: 'Material handling',
      status: 'WALKING',
      reactionTime: 0.8,
      currentWaypointIndex: 0,
      path: [
        { x: 80, y: 50 },
        { x: 35, y: 50 },
        { x: 80, y: 50 },
      ],
    },
  },
  {
    id: 'sc-3-highspeed',
    name: 'Scenario 3: High-Speed AMR & Complex Maintenance',
    description: 'Robot runs at maximum permitted transit speed (2.4 m/s) while a maintenance worker performs valve servicing nearby. Higher velocity substantially expands dynamic safety requirement.',
    expectedOutcome: 'WARNING',
    duration: 25,
    safetyRules: {
      ...DEFAULT_SAFETY_RULES,
      safetyMargin: 1.2,
      baseDistance: 1.5,
    },
    initialRobot: {
      id: 'amr-02',
      name: 'MiR1350 High-Speed Carrier',
      type: 'Logistics AMR',
      position: { x: 25, y: 45 },
      currentSpeed: 2.4,
      maxSpeed: 2.5,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 1.2,
      baseRadius: 1.2,
      currentWaypointIndex: 0,
      path: [
        { x: 25, y: 45 },
        { x: 75, y: 45 },
        { x: 25, y: 45 },
      ],
    },
    initialHuman: {
      id: 'worker-03',
      name: 'Mike Ross (Maintenance Specialist)',
      position: { x: 48, y: 52 },
      currentSpeed: 0.4,
      expectedSpeed: 0.5,
      direction: 0,
      task: 'Maintenance',
      status: 'WALKING',
      reactionTime: 0.9,
      currentWaypointIndex: 0,
      path: [
        { x: 48, y: 52 },
        { x: 55, y: 49 },
        { x: 48, y: 52 },
      ],
    },
  },
];

export const FAILURE_EDGE_CASES: ScenarioDefinition[] = [
  {
    id: 'edge-1-coincident',
    name: 'Edge Case 1: Coincident Initial Position (Distance = 0)',
    description: 'Human and robot initialized at the exact same plant coordinate (x: 50, y: 50). Verifies immediate EMERGENCY state trigger and divide-by-zero prevention.',
    expectedOutcome: 'EMERGENCY',
    duration: 10,
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR Bot',
      type: 'Industrial AGV',
      position: { x: 50, y: 50 },
      currentSpeed: 0.0,
      maxSpeed: 2.0,
      direction: 0,
      status: 'IDLE',
      stoppingTime: 0.5,
      baseRadius: 1.0,
      currentWaypointIndex: 0,
      path: [{ x: 50, y: 50 }, { x: 50, y: 50 }],
    },
    initialHuman: {
      id: 'worker-01',
      name: 'Worker',
      position: { x: 50, y: 50 },
      currentSpeed: 0.0,
      expectedSpeed: 1.0,
      direction: 0,
      task: 'Inspection',
      status: 'IDLE',
      reactionTime: 0.7,
      currentWaypointIndex: 0,
      path: [{ x: 50, y: 50 }, { x: 50, y: 50 }],
    },
  },
  {
    id: 'edge-2-zero-speed',
    name: 'Edge Case 2: Zero Robot Speed (Stationary Robot)',
    description: 'Robot is completely stationary (0.0 m/s). System must evaluate minimum static base distance and not trigger false dynamic high-speed alarms.',
    expectedOutcome: 'SAFE',
    duration: 15,
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-idle',
      name: 'Docked AMR',
      type: 'Industrial AGV',
      position: { x: 50, y: 50 },
      currentSpeed: 0.0,
      maxSpeed: 2.0,
      direction: 0,
      status: 'IDLE',
      stoppingTime: 0.5,
      baseRadius: 1.0,
      currentWaypointIndex: 0,
      path: [{ x: 50, y: 50 }, { x: 50, y: 50 }],
    },
    initialHuman: {
      id: 'worker-walk',
      name: 'Passing Worker',
      position: { x: 50, y: 56 }, // 6m away
      currentSpeed: 1.2,
      expectedSpeed: 1.2,
      direction: 0,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.7,
      currentWaypointIndex: 0,
      path: [
        { x: 30, y: 56 },
        { x: 70, y: 56 },
      ],
    },
  },
  {
    id: 'edge-3-excessive-speed',
    name: 'Edge Case 3: Excessive / Out-of-Bounds Robot Velocity',
    description: 'Robot speed set to 9.5 m/s (far beyond physical 2.5 m/s limit). System detects anomaly, flags validation warning, and limits unsafe extrapolation.',
    expectedOutcome: 'UNSAFE',
    duration: 15,
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-speeding',
      name: 'Uncalibrated High-Speed AMR',
      type: 'Industrial AGV',
      position: { x: 20, y: 50 },
      currentSpeed: 9.5,
      maxSpeed: 2.5,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 3.5,
      baseRadius: 1.0,
      currentWaypointIndex: 0,
      path: [
        { x: 20, y: 50 },
        { x: 80, y: 50 },
      ],
    },
    initialHuman: {
      id: 'worker-01',
      name: 'Worker',
      position: { x: 45, y: 50 },
      currentSpeed: 1.0,
      expectedSpeed: 1.0,
      direction: Math.PI,
      task: 'Material handling',
      status: 'WALKING',
      reactionTime: 0.8,
      currentWaypointIndex: 0,
      path: [
        { x: 45, y: 50 },
        { x: 35, y: 50 },
      ],
    },
  },
  {
    id: 'edge-4-negative-speed',
    name: 'Edge Case 4: Negative Velocity Telemetry Sensor Glitch',
    description: 'Telemetry sensor anomaly reports negative human speed (-1.5 m/s). System sanitizes negative velocity and reports parameter validation error.',
    expectedOutcome: 'SAFE',
    duration: 10,
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR Bot',
      type: 'Industrial AGV',
      position: { x: 20, y: 20 },
      currentSpeed: 1.0,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.6,
      baseRadius: 1.0,
      currentWaypointIndex: 0,
      path: [{ x: 20, y: 20 }, { x: 50, y: 20 }],
    },
    initialHuman: {
      id: 'worker-anomaly',
      name: 'Worker',
      position: { x: 70, y: 70 },
      currentSpeed: -1.5, // Negative velocity glitch
      expectedSpeed: 1.0,
      direction: 0,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.7,
      currentWaypointIndex: 0,
      path: [{ x: 70, y: 70 }, { x: 80, y: 70 }],
    },
  },
  {
    id: 'edge-5-out-of-bounds',
    name: 'Edge Case 5: Out-of-Bounds Plant Boundary Overflow',
    description: 'Human coordinates placed at (x: 125, y: 110) outside the 100m plant boundary. System flags boundary violation and validates layout constraints.',
    expectedOutcome: 'SAFE',
    duration: 10,
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR Bot',
      type: 'Industrial AGV',
      position: { x: 50, y: 50 },
      currentSpeed: 1.2,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.6,
      baseRadius: 1.0,
      currentWaypointIndex: 0,
      path: [{ x: 50, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'worker-oob',
      name: 'Worker OOB',
      position: { x: 125, y: 110 }, // Out of bounds
      currentSpeed: 1.0,
      expectedSpeed: 1.0,
      direction: 0,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.7,
      currentWaypointIndex: 0,
      path: [{ x: 125, y: 110 }, { x: 130, y: 110 }],
    },
  },
  {
    id: 'edge-6-excessive-margin',
    name: 'Edge Case 6: Extremely Large Safety Margin Setting',
    description: 'Safety margin configured to 15.0m buffer. Decision engine expands required dynamic zone to encompass whole aisle, flagging conservative WARNING.',
    expectedOutcome: 'WARNING',
    duration: 10,
    safetyRules: {
      ...DEFAULT_SAFETY_RULES,
      safetyMargin: 15.0, // High margin
    },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR Bot',
      type: 'Industrial AGV',
      position: { x: 30, y: 40 },
      currentSpeed: 1.0,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.6,
      baseRadius: 1.0,
      currentWaypointIndex: 0,
      path: [{ x: 30, y: 40 }, { x: 60, y: 40 }],
    },
    initialHuman: {
      id: 'worker-01',
      name: 'Worker',
      position: { x: 45, y: 40 }, // 15m away
      currentSpeed: 1.0,
      expectedSpeed: 1.0,
      direction: 0,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.7,
      currentWaypointIndex: 0,
      path: [{ x: 45, y: 40 }, { x: 55, y: 40 }],
    },
  },
];
