import type { ScenarioDefinition, PlantLayout } from '../../types';
import { DEFAULT_SAFETY_RULES, DEFAULT_ENVIRONMENT_CONFIG } from '../safety/safetyEngine';

export const DEFAULT_PLANT_LAYOUT: PlantLayout = {
  id: 'layout-process-plant-01',
  name: 'Heavy Chemical Process Plant - Unit 4B',
  width: 100, // 100 meters
  height: 100, // 100 meters
  gridSize: 5,
  objects: [
    {
      id: 'eq-1',
      name: 'Fractionation Column A',
      type: 'equipment',
      x: 15,
      y: 15,
      width: 18,
      height: 14,
      color: '#3b82f6',
      description: 'Primary distillation and fractionation unit',
    },
    {
      id: 'eq-2',
      name: 'High Pressure Reactor 02',
      type: 'equipment',
      x: 65,
      y: 15,
      width: 20,
      height: 16,
      color: '#06b6d4',
      description: 'Catalytic continuous chemical reactor',
    },
    {
      id: 'eq-3',
      name: 'Compressor Skid & Pumps',
      type: 'equipment',
      x: 15,
      y: 65,
      width: 22,
      height: 15,
      color: '#6366f1',
      description: 'Feed gas compression and hydraulic pumps',
    },
    {
      id: 'rs-1',
      name: 'Robotic Valve Actuation Station',
      type: 'robot_station',
      x: 50,
      y: 45,
      width: 12,
      height: 12,
      color: '#f59e0b',
      description: 'Autonomous mobile robot (AMR) docking & payload station',
    },
    {
      id: 'ws-1',
      name: 'Technician Inspection Bay',
      type: 'workstation',
      x: 75,
      y: 70,
      width: 14,
      height: 12,
      color: '#10b981',
      description: 'Manual sample extraction and quality station',
    },
    {
      id: 'rz-1',
      name: 'High Voltage / Flammable Zone',
      type: 'restricted_zone',
      x: 40,
      y: 10,
      width: 18,
      height: 12,
      color: '#ef4444',
      restrictedReason: 'Explosive atmosphere hazard (ATEX Zone 1)',
    },
  ],
};

export const PREDEFINED_SCENARIOS: ScenarioDefinition[] = [
  // --- SINGLE AGENT SCENARIOS (Review 1 Baseline & Canonical N=1, M=1) ---
  {
    id: 'sc-1-normal',
    name: 'Scenario 1: Head-On Process Walkway',
    description: 'Autonomous mobile robot transporting chemical samples along main process corridor while an inspection engineer approaches in the opposite direction.',
    expectedOutcome: 'WARNING',
    duration: 25,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-Transporter-01',
      type: 'Heavy Industrial AMR',
      position: { x: 10, y: 50 },
      currentSpeed: 1.5,
      maxSpeed: 2.5,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [
        { x: 10, y: 50 },
        { x: 35, y: 50 },
        { x: 65, y: 50 },
        { x: 90, y: 50 },
      ],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Plant Operator (Rajesh)',
      position: { x: 80, y: 50 },
      currentSpeed: 1.2,
      expectedSpeed: 1.2,
      direction: Math.PI,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [
        { x: 80, y: 50 },
        { x: 55, y: 50 },
        { x: 30, y: 50 },
        { x: 10, y: 50 },
      ],
    },
    robots: [
      {
        id: 'amr-01',
        name: 'AMR-Transporter-01',
        type: 'Heavy Industrial AMR',
        position: { x: 10, y: 50 },
        currentSpeed: 1.5,
        maxSpeed: 2.5,
        direction: 0,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 10, y: 50 }, { x: 35, y: 50 }, { x: 65, y: 50 }, { x: 90, y: 50 }],
      }
    ],
    humans: [
      {
        id: 'human-01',
        name: 'Plant Operator (Rajesh)',
        position: { x: 80, y: 50 },
        currentSpeed: 1.2,
        expectedSpeed: 1.2,
        direction: Math.PI,
        task: 'Inspection',
        status: 'WALKING',
        reactionTime: 0.5,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 80, y: 50 }, { x: 55, y: 50 }, { x: 30, y: 50 }, { x: 10, y: 50 }],
      }
    ]
  },
  {
    id: 'sc-2-blind-corner',
    name: 'Scenario 2: Perpendicular Blind Corner',
    description: 'AMR emerging from between fractionation columns while maintenance lead crosses perpendicular corridor with obstructed field of view.',
    expectedOutcome: 'UNSAFE',
    duration: 20,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-Transporter-01',
      type: 'Heavy Industrial AMR',
      position: { x: 50, y: 15 },
      currentSpeed: 1.2,
      maxSpeed: 2.5,
      direction: Math.PI / 2,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [
        { x: 50, y: 15 },
        { x: 50, y: 40 },
        { x: 50, y: 65 },
        { x: 50, y: 90 },
      ],
    },
    initialHuman: {
      id: 'human-02',
      name: 'Maintenance Lead (Priya)',
      position: { x: 15, y: 50 },
      currentSpeed: 1.4,
      expectedSpeed: 1.4,
      direction: 0,
      task: 'Maintenance',
      status: 'WALKING',
      reactionTime: 0.7,
      currentWaypointIndex: 0,
      isActive: true,
      path: [
        { x: 15, y: 50 },
        { x: 45, y: 50 },
        { x: 60, y: 50 },
        { x: 85, y: 50 },
      ],
    },
    robots: [
      {
        id: 'amr-01',
        name: 'AMR-Transporter-01',
        type: 'Heavy Industrial AMR',
        position: { x: 50, y: 15 },
        currentSpeed: 1.2,
        maxSpeed: 2.5,
        direction: Math.PI / 2,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 50, y: 15 }, { x: 50, y: 40 }, { x: 50, y: 65 }, { x: 50, y: 90 }],
      }
    ],
    humans: [
      {
        id: 'human-02',
        name: 'Maintenance Lead (Priya)',
        position: { x: 15, y: 50 },
        currentSpeed: 1.4,
        expectedSpeed: 1.4,
        direction: 0,
        task: 'Maintenance',
        status: 'WALKING',
        reactionTime: 0.7,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 15, y: 50 }, { x: 45, y: 50 }, { x: 60, y: 50 }, { x: 85, y: 50 }],
      }
    ]
  },
  {
    id: 'sc-3-diverge',
    name: 'Scenario 3: High-Speed Overtaking Corridor',
    description: 'AMR and technician travelling along parallel logistics lanes in the same direction, testing dynamic boundary adaptation under low relative approach velocity.',
    expectedOutcome: 'SAFE',
    duration: 30,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-Transporter-01',
      type: 'Heavy Industrial AMR',
      position: { x: 10, y: 35 },
      currentSpeed: 1.6,
      maxSpeed: 2.5,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [
        { x: 10, y: 35 },
        { x: 40, y: 35 },
        { x: 70, y: 35 },
        { x: 90, y: 35 },
      ],
    },
    initialHuman: {
      id: 'human-03',
      name: 'Field Technician (Suresh)',
      position: { x: 25, y: 42 },
      currentSpeed: 1.0,
      expectedSpeed: 1.0,
      direction: 0,
      task: 'Material handling',
      status: 'WALKING',
      reactionTime: 0.6,
      currentWaypointIndex: 0,
      isActive: true,
      path: [
        { x: 25, y: 42 },
        { x: 50, y: 42 },
        { x: 75, y: 42 },
        { x: 95, y: 42 },
      ],
    },
    robots: [
      {
        id: 'amr-01',
        name: 'AMR-Transporter-01',
        type: 'Heavy Industrial AMR',
        position: { x: 10, y: 35 },
        currentSpeed: 1.6,
        maxSpeed: 2.5,
        direction: 0,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 10, y: 35 }, { x: 40, y: 35 }, { x: 70, y: 35 }, { x: 90, y: 35 }],
      }
    ],
    humans: [
      {
        id: 'human-03',
        name: 'Field Technician (Suresh)',
        position: { x: 25, y: 42 },
        currentSpeed: 1.0,
        expectedSpeed: 1.0,
        direction: 0,
        task: 'Material handling',
        status: 'WALKING',
        reactionTime: 0.6,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 25, y: 42 }, { x: 50, y: 42 }, { x: 75, y: 42 }, { x: 95, y: 42 }],
      }
    ]
  },

  // --- REVIEW 2 MULTI-AGENT SCENARIOS (MULTI-01, MULTI-02, MULTI-03) ---
  {
    id: 'sc-multi-01-cross',
    name: 'MULTI-01: Two AMRs Crossing Intersection (2 AMRs + 2 Humans)',
    description: 'Two autonomous mobile robots crossing a busy plant intersection perpendicularly while two field operators perform crosswalk inspections. Evaluates Robot-Robot and Robot-Human pairwise safety arbitration.',
    expectedOutcome: 'WARNING',
    duration: 30,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-Alpha (R1)',
      type: 'Heavy Industrial AMR',
      position: { x: 10, y: 50 },
      currentSpeed: 1.5,
      maxSpeed: 2.5,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 10, y: 50 }, { x: 45, y: 50 }, { x: 70, y: 50 }, { x: 90, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Process Operator (H1)',
      position: { x: 80, y: 50 },
      currentSpeed: 1.0,
      expectedSpeed: 1.0,
      direction: Math.PI,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 80, y: 50 }, { x: 55, y: 50 }, { x: 30, y: 50 }, { x: 10, y: 50 }],
    },
    robots: [
      {
        id: 'amr-01',
        name: 'AMR-Alpha (R1)',
        type: 'Heavy Industrial AMR',
        position: { x: 10, y: 50 },
        currentSpeed: 1.5,
        maxSpeed: 2.5,
        direction: 0,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 10, y: 50 }, { x: 45, y: 50 }, { x: 70, y: 50 }, { x: 90, y: 50 }],
      },
      {
        id: 'amr-02',
        name: 'AMR-Beta (R2)',
        type: 'Logistics Tugger AMR',
        position: { x: 50, y: 15 },
        currentSpeed: 1.3,
        maxSpeed: 2.0,
        direction: Math.PI / 2,
        status: 'MOVING',
        stoppingTime: 0.9,
        baseRadius: 0.9,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 50, y: 15 }, { x: 50, y: 45 }, { x: 50, y: 70 }, { x: 50, y: 90 }],
      }
    ],
    humans: [
      {
        id: 'human-01',
        name: 'Process Operator (H1)',
        position: { x: 80, y: 50 },
        currentSpeed: 1.0,
        expectedSpeed: 1.0,
        direction: Math.PI,
        task: 'Inspection',
        status: 'WALKING',
        reactionTime: 0.5,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 80, y: 50 }, { x: 55, y: 50 }, { x: 30, y: 50 }, { x: 10, y: 50 }],
      },
      {
        id: 'human-02',
        name: 'Safety Inspector (H2)',
        position: { x: 35, y: 75 },
        currentSpeed: 1.1,
        expectedSpeed: 1.1,
        direction: -Math.PI / 2,
        task: 'Maintenance',
        status: 'WALKING',
        reactionTime: 0.6,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 35, y: 75 }, { x: 50, y: 55 }, { x: 65, y: 35 }, { x: 85, y: 20 }],
      }
    ]
  },
  {
    id: 'sc-multi-02-aisle',
    name: 'MULTI-02: AMR Through Worker-Heavy Aisle (1 AMR + 2 Humans)',
    description: 'High-speed logistics AMR traversing narrow central aisle between equipment skids with multiple maintenance workers walking and performing inspection tasks.',
    expectedOutcome: 'UNSAFE',
    duration: 25,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-Transporter (R1)',
      type: 'Heavy Industrial AMR',
      position: { x: 15, y: 40 },
      currentSpeed: 1.8,
      maxSpeed: 2.5,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 15, y: 40 }, { x: 45, y: 40 }, { x: 75, y: 40 }, { x: 95, y: 40 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Lead Mechanic (H1)',
      position: { x: 55, y: 42 },
      currentSpeed: 0.8,
      expectedSpeed: 0.8,
      direction: Math.PI,
      task: 'Maintenance',
      status: 'WALKING',
      reactionTime: 0.6,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 55, y: 42 }, { x: 40, y: 42 }, { x: 25, y: 42 }, { x: 10, y: 42 }],
    },
    robots: [
      {
        id: 'amr-01',
        name: 'AMR-Transporter (R1)',
        type: 'Heavy Industrial AMR',
        position: { x: 15, y: 40 },
        currentSpeed: 1.8,
        maxSpeed: 2.5,
        direction: 0,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 15, y: 40 }, { x: 45, y: 40 }, { x: 75, y: 40 }, { x: 95, y: 40 }],
      }
    ],
    humans: [
      {
        id: 'human-01',
        name: 'Lead Mechanic (H1)',
        position: { x: 55, y: 42 },
        currentSpeed: 0.8,
        expectedSpeed: 0.8,
        direction: Math.PI,
        task: 'Maintenance',
        status: 'WALKING',
        reactionTime: 0.6,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 55, y: 42 }, { x: 40, y: 42 }, { x: 25, y: 42 }, { x: 10, y: 42 }],
      },
      {
        id: 'human-02',
        name: 'Quality Auditor (H2)',
        position: { x: 75, y: 38 },
        currentSpeed: 0.9,
        expectedSpeed: 0.9,
        direction: Math.PI,
        task: 'Quality checking',
        status: 'WALKING',
        reactionTime: 0.5,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 75, y: 38 }, { x: 60, y: 38 }, { x: 45, y: 38 }, { x: 20, y: 38 }],
      }
    ]
  },
  {
    id: 'sc-multi-03-converge',
    name: 'MULTI-03: Multi-Agent Process Plant Convergence (2 AMRs + 2 Humans)',
    description: 'High-density convergence zone near Reactor 02 where two AMRs deliver catalysts while two technicians coordinate valve actuation under wet washdown floor conditions.',
    expectedOutcome: 'UNSAFE',
    duration: 30,
    environment: {
      floorCondition: 'WET_WASHDOWN',
      frictionCoefficient: 0.65,
      temperature: 30,
      pressure: 1.013,
      sensorDegradationFactor: 0.10,
      ambientNotes: 'Reactor floor washdown zone (μ=0.65, 30°C)'
    },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'Catalyst Feeder AMR (R1)',
      type: 'Heavy Industrial AMR',
      position: { x: 30, y: 30 },
      currentSpeed: 1.4,
      maxSpeed: 2.0,
      direction: Math.PI / 4,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 30, y: 30 }, { x: 55, y: 45 }, { x: 75, y: 60 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Reactor Lead (H1)',
      position: { x: 70, y: 60 },
      currentSpeed: 1.0,
      expectedSpeed: 1.0,
      direction: -3 * Math.PI / 4,
      task: 'Maintenance',
      status: 'WALKING',
      reactionTime: 0.6,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 70, y: 60 }, { x: 55, y: 45 }, { x: 30, y: 30 }],
    },
    robots: [
      {
        id: 'amr-01',
        name: 'Catalyst Feeder AMR (R1)',
        type: 'Heavy Industrial AMR',
        position: { x: 30, y: 30 },
        currentSpeed: 1.4,
        maxSpeed: 2.0,
        direction: Math.PI / 4,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 30, y: 30 }, { x: 55, y: 45 }, { x: 75, y: 60 }],
      },
      {
        id: 'amr-02',
        name: 'Sample Carrier AMR (R2)',
        type: 'Light Carrier AGV',
        position: { x: 75, y: 30 },
        currentSpeed: 1.3,
        maxSpeed: 2.0,
        direction: 3 * Math.PI / 4,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 75, y: 30 }, { x: 55, y: 45 }, { x: 30, y: 60 }],
      }
    ],
    humans: [
      {
        id: 'human-01',
        name: 'Reactor Lead (H1)',
        position: { x: 70, y: 60 },
        currentSpeed: 1.0,
        expectedSpeed: 1.0,
        direction: -3 * Math.PI / 4,
        task: 'Maintenance',
        status: 'WALKING',
        reactionTime: 0.6,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 70, y: 60 }, { x: 55, y: 45 }, { x: 30, y: 30 }],
      },
      {
        id: 'human-02',
        name: 'Sampling Tech (H2)',
        position: { x: 30, y: 60 },
        currentSpeed: 1.1,
        expectedSpeed: 1.1,
        direction: -Math.PI / 4,
        task: 'Material handling',
        status: 'WALKING',
        reactionTime: 0.5,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 30, y: 60 }, { x: 55, y: 45 }, { x: 75, y: 30 }],
      }
    ]
  }
];

export const FAILURE_EDGE_CASES: ScenarioDefinition[] = [
  // --- SINGLE AGENT EDGE CASES (EC-01 to EC-06: Review 1 Baseline) ---
  {
    id: 'edge-01-stationary-close',
    name: 'EC-01: Zero Speed Stationary Proximity',
    description: 'Robot and human both stationary at 1.2m proximity. Verifies base clearance without velocity division singularities.',
    expectedOutcome: 'UNSAFE',
    duration: 10,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 50, y: 50 },
      currentSpeed: 0,
      maxSpeed: 2.0,
      direction: 0,
      status: 'IDLE',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 50, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Operator',
      position: { x: 50, y: 51.2 },
      currentSpeed: 0,
      expectedSpeed: 0,
      direction: 0,
      task: 'Inspection',
      status: 'WORKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 50, y: 51.2 }],
    },
  },
  {
    id: 'edge-02-max-velocity-head-on',
    name: 'EC-02: Maximum Velocity Extreme Approach',
    description: 'AMR operating at 3.5m/s sprint towards running operator (2.5m/s) with 1.5m separation. Tests emergency boundary expansion.',
    expectedOutcome: 'EMERGENCY',
    duration: 10,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES, emergencyThreshold: 2.0 },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 45, y: 50 },
      currentSpeed: 3.5,
      maxSpeed: 3.5,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 1.2,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 45, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Operator',
      position: { x: 46.5, y: 50 },
      currentSpeed: 2.5,
      expectedSpeed: 2.5,
      direction: Math.PI,
      task: 'Maintenance',
      status: 'EVACUATING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 46.5, y: 50 }, { x: 40, y: 50 }],
    },
  },
  {
    id: 'edge-03-high-reaction-time',
    name: 'EC-03: Ultra High Reaction Time Latency',
    description: 'Human worker wearing heavy bulky hazmat suit with degraded reaction latency (1.8s). Assesses reaction multiplier scaling.',
    expectedOutcome: 'UNSAFE',
    duration: 10,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 40, y: 50 },
      currentSpeed: 1.5,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 40, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Hazmat Tech',
      position: { x: 43.5, y: 50 },
      currentSpeed: 1.0,
      expectedSpeed: 1.0,
      direction: Math.PI,
      task: 'Cleaning',
      status: 'WALKING',
      reactionTime: 1.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 43.5, y: 50 }, { x: 30, y: 50 }],
    },
  },
  {
    id: 'edge-04-high-risk-inspection',
    name: 'EC-04: High Risk Inspection Area Tight Clearance',
    description: 'Critical valve checking task with 1.4x safety multiplier in restricted process corridor.',
    expectedOutcome: 'WARNING',
    duration: 10,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 30, y: 50 },
      currentSpeed: 1.0,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 30, y: 50 }, { x: 50, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Senior Inspector',
      position: { x: 34.5, y: 50 },
      currentSpeed: 0.5,
      expectedSpeed: 0.5,
      direction: Math.PI,
      task: 'Maintenance',
      status: 'WORKING',
      reactionTime: 0.6,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 34.5, y: 50 }, { x: 25, y: 50 }],
    },
  },
  {
    id: 'edge-05-colinear-opposite',
    name: 'EC-05: Co-linear Opposite Trajectory Head-On',
    description: 'Exact opposite co-linear approach with zero lateral displacement. Tests directional approach vector scaling (1.5x factor).',
    expectedOutcome: 'EMERGENCY',
    duration: 10,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES, emergencyThreshold: 1.8 },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 48, y: 50 },
      currentSpeed: 1.8,
      maxSpeed: 2.5,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 48, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Operator',
      position: { x: 49.5, y: 50 },
      currentSpeed: 1.5,
      expectedSpeed: 1.5,
      direction: Math.PI,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 49.5, y: 50 }, { x: 40, y: 50 }],
    },
  },
  {
    id: 'edge-06-zero-buffer-tolerance',
    name: 'EC-06: Zero Buffer Boundary Tolerance',
    description: 'Zero additional safety margin (Msafety = 0.0m) stress test. Verifies core kinematic formula stability without synthetic padding.',
    expectedOutcome: 'EMERGENCY',
    duration: 10,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: {
      ...DEFAULT_SAFETY_RULES,
      safetyMargin: 0.0,
      baseDistance: 0.5,
      emergencyThreshold: 1.0,
    },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 48.5, y: 50 },
      currentSpeed: 1.5,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 48.5, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Operator',
      position: { x: 49.2, y: 50 },
      currentSpeed: 1.2,
      expectedSpeed: 1.2,
      direction: Math.PI,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 49.2, y: 50 }, { x: 40, y: 50 }],
    },
  },

  // --- REVIEW 2 PHASE 1 ENVIRONMENTAL EDGE CASES (EC-07 to EC-12) ---
  {
    id: 'edge-07-low-friction-slick',
    name: 'EC-07: Low Floor Friction Traction Loss (μ = 0.20)',
    description: 'Cold storage / chemical frost slick (friction μ = 0.20). Stopping distance component expands 5x due to reduced tire-to-floor adhesion.',
    expectedOutcome: 'UNSAFE',
    duration: 15,
    environment: {
      temperature: -10,
      pressure: 1.013,
      floorCondition: 'COLD_FROST',
      frictionCoefficient: 0.20,
      sensorDegradationFactor: 0.05,
      ambientNotes: 'Low-traction frost floor'
    },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 30, y: 50 },
      currentSpeed: 1.4,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 1.0,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 30, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Technician',
      position: { x: 36, y: 50 },
      currentSpeed: 0.8,
      expectedSpeed: 0.8,
      direction: Math.PI,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.6,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 36, y: 50 }, { x: 20, y: 50 }],
    },
  },
  {
    id: 'edge-08-sensor-haze-degradation',
    name: 'EC-08: Sensor Degradation & Heavy Steam Haze (η = 0.50)',
    description: 'Severe process steam obscuration degrading LiDAR and optical sensor reliability by 50%. Expands perception uncertainty buffer.',
    expectedOutcome: 'WARNING',
    duration: 15,
    environment: {
      temperature: 35,
      pressure: 1.013,
      floorCondition: 'DRY_CLEAN',
      frictionCoefficient: 1.0,
      sensorDegradationFactor: 0.50,
      ambientNotes: 'Process steam haze'
    },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 30, y: 50 },
      currentSpeed: 1.2,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 30, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Inspector',
      position: { x: 36, y: 50 },
      currentSpeed: 0.8,
      expectedSpeed: 0.8,
      direction: Math.PI,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 36, y: 50 }, { x: 20, y: 50 }],
    },
  },
  {
    id: 'edge-09-ambient-thermal-stress',
    name: 'EC-09: Ambient Temperature Deviation (55°C Furnace Area)',
    description: 'Elevated temperature thermal stress (55°C) near plant furnace area modulating worker reaction latency and ambient factor.',
    expectedOutcome: 'WARNING',
    duration: 15,
    environment: {
      temperature: 55,
      pressure: 1.013,
      floorCondition: 'DRY_CLEAN',
      frictionCoefficient: 1.0,
      sensorDegradationFactor: 0.05,
      ambientNotes: 'Furnace corridor heat stress'
    },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 30, y: 50 },
      currentSpeed: 1.2,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 30, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Boiler Tech',
      position: { x: 35.5, y: 50 },
      currentSpeed: 0.8,
      expectedSpeed: 0.8,
      direction: Math.PI,
      task: 'Maintenance',
      status: 'WALKING',
      reactionTime: 0.6,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 35.5, y: 50 }, { x: 20, y: 50 }],
    },
  },
  {
    id: 'edge-10-pressure-deviation',
    name: 'EC-10: Atmospheric Pressure Deviation (0.70 bar & 2.20 bar)',
    description: 'High-altitude process chamber and pressurized vessel corridor tests pressure scaling stability.',
    expectedOutcome: 'SAFE',
    duration: 15,
    environment: {
      temperature: 25,
      pressure: 2.20,
      floorCondition: 'DRY_CLEAN',
      frictionCoefficient: 1.0,
      sensorDegradationFactor: 0.0,
      ambientNotes: 'Pressurized autoclave hall'
    },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 20, y: 50 },
      currentSpeed: 1.0,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 20, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Process Operator',
      position: { x: 36, y: 50 },
      currentSpeed: 0.6,
      expectedSpeed: 0.6,
      direction: Math.PI,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 36, y: 50 }, { x: 10, y: 50 }],
    },
  },
  {
    id: 'edge-11-invalid-input-clamping',
    name: 'EC-11: Invalid Environmental Input Clamping (Negative & Overflow)',
    description: 'Stress tests sanitizer against unphysical values: friction μ = -0.5, temperature = 180°C, sensor degradation = 1.8. Verifies auto-clamping.',
    expectedOutcome: 'UNSAFE',
    duration: 15,
    environment: {
      temperature: 180,
      pressure: 8.5,
      floorCondition: 'OIL_CHEMICAL_SLICK',
      frictionCoefficient: -0.5,
      sensorDegradationFactor: 1.8,
      ambientNotes: 'Unphysical malformed inputs'
    },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 30, y: 50 },
      currentSpeed: 1.5,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 30, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Safety Auditor',
      position: { x: 35.5, y: 50 },
      currentSpeed: 0.8,
      expectedSpeed: 0.8,
      direction: Math.PI,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 35.5, y: 50 }, { x: 20, y: 50 }],
    },
  },
  {
    id: 'edge-12-combined-adverse-factors',
    name: 'EC-12: Combined Adverse Multi-Factor Stress (Oil Slick + Haze + Heat)',
    description: 'Worst-case plant disaster scenario combining oil slick (μ=0.35), 45°C ambient heat, and 40% optical smoke degradation with tight 0.8m proximity.',
    expectedOutcome: 'EMERGENCY',
    duration: 15,
    environment: {
      temperature: 45,
      pressure: 1.013,
      floorCondition: 'OIL_CHEMICAL_SLICK',
      frictionCoefficient: 0.35,
      sensorDegradationFactor: 0.40,
      ambientNotes: 'Multiple adverse compound factors'
    },
    safetyRules: { ...DEFAULT_SAFETY_RULES, emergencyThreshold: 1.0 },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 30, y: 50 },
      currentSpeed: 1.8,
      maxSpeed: 2.5,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 1.0,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 30, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Emergency Responder',
      position: { x: 30.8, y: 50 },
      currentSpeed: 1.5,
      expectedSpeed: 1.5,
      direction: Math.PI,
      task: 'Maintenance',
      status: 'EVACUATING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 30.8, y: 50 }, { x: 20, y: 50 }],
    },
  },

  // --- REVIEW 2 PHASE 2 MULTI-AGENT FAILURE CASES (MULTI-EC-01 to MULTI-EC-06) ---
  {
    id: 'multi-ec-01-coincident-pair',
    name: 'MULTI-EC-01: Two Agents at Exactly Same Position (Separation=0.0m)',
    description: 'AMR-1 and Human-1 placed at identical coordinate (50, 50). Verifies EMERGENCY trigger without divide-by-zero or NaN singularity.',
    expectedOutcome: 'EMERGENCY',
    duration: 5,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 50, y: 50 },
      currentSpeed: 1.0,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 50, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Worker-01',
      position: { x: 50, y: 50 },
      currentSpeed: 1.0,
      expectedSpeed: 1.0,
      direction: 0,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 50, y: 50 }],
    },
  },
  {
    id: 'multi-ec-02-four-coincident',
    name: 'MULTI-EC-02: Four Agents Coincident Coordinate Singularity',
    description: '2 AMRs and 2 Humans all initialized at (40, 40). Verifies all 6 pairwise evaluations trigger EMERGENCY gracefully without crash.',
    expectedOutcome: 'EMERGENCY',
    duration: 5,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 40, y: 40 },
      currentSpeed: 1.0,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 40, y: 40 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Human-01',
      position: { x: 40, y: 40 },
      currentSpeed: 1.0,
      expectedSpeed: 1.0,
      direction: 0,
      task: 'Inspection',
      status: 'WALKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 40, y: 40 }],
    },
    robots: [
      {
        id: 'amr-01',
        name: 'AMR-01',
        type: 'Industrial AGV',
        position: { x: 40, y: 40 },
        currentSpeed: 1.0,
        maxSpeed: 2.0,
        direction: 0,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 40, y: 40 }],
      },
      {
        id: 'amr-02',
        name: 'AMR-02',
        type: 'Industrial AGV',
        position: { x: 40, y: 40 },
        currentSpeed: 1.0,
        maxSpeed: 2.0,
        direction: 0,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 40, y: 40 }],
      }
    ],
    humans: [
      {
        id: 'human-01',
        name: 'Human-01',
        position: { x: 40, y: 40 },
        currentSpeed: 1.0,
        expectedSpeed: 1.0,
        direction: 0,
        task: 'Inspection',
        status: 'WALKING',
        reactionTime: 0.5,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 40, y: 40 }],
      },
      {
        id: 'human-02',
        name: 'Human-02',
        position: { x: 40, y: 40 },
        currentSpeed: 1.0,
        expectedSpeed: 1.0,
        direction: 0,
        task: 'Maintenance',
        status: 'WALKING',
        reactionTime: 0.5,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 40, y: 40 }],
      }
    ]
  },
  {
    id: 'multi-ec-03-fleet-head-on',
    name: 'MULTI-EC-03: Two Robots Moving Direct Head-On',
    description: 'Two AMRs traveling towards each other in the same lane at 2.0 m/s each with 3.0m separation. Verifies Robot-Robot threat detection.',
    expectedOutcome: 'UNSAFE',
    duration: 10,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 40, y: 50 },
      currentSpeed: 2.0,
      maxSpeed: 2.5,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 40, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Distant Worker',
      position: { x: 80, y: 80 },
      currentSpeed: 0.5,
      expectedSpeed: 0.5,
      direction: 0,
      task: 'Inspection',
      status: 'WORKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 80, y: 80 }],
    },
    robots: [
      {
        id: 'amr-01',
        name: 'AMR-01',
        type: 'Industrial AGV',
        position: { x: 40, y: 50 },
        currentSpeed: 2.0,
        maxSpeed: 2.5,
        direction: 0,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 40, y: 50 }, { x: 60, y: 50 }],
      },
      {
        id: 'amr-02',
        name: 'AMR-02',
        type: 'Industrial AGV',
        position: { x: 43, y: 50 },
        currentSpeed: 2.0,
        maxSpeed: 2.5,
        direction: Math.PI,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 43, y: 50 }, { x: 20, y: 50 }],
      }
    ],
    humans: [
      {
        id: 'human-01',
        name: 'Distant Worker',
        position: { x: 80, y: 80 },
        currentSpeed: 0.5,
        expectedSpeed: 0.5,
        direction: 0,
        task: 'Inspection',
        status: 'WORKING',
        reactionTime: 0.5,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 80, y: 80 }],
      }
    ]
  },
  {
    id: 'multi-ec-04-multi-human-surround',
    name: 'MULTI-EC-04: One Robot Surrounded by Multiple Humans',
    description: 'AMR surrounded by 3 workers at varying distances (1.2m, 3.5m, 8.0m). Verifies closest breach (1.2m) is arbitrated as highest threat.',
    expectedOutcome: 'UNSAFE',
    duration: 10,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 50, y: 50 },
      currentSpeed: 1.5,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 50, y: 50 }, { x: 60, y: 50 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Close Worker',
      position: { x: 51.2, y: 50 },
      currentSpeed: 1.0,
      expectedSpeed: 1.0,
      direction: Math.PI,
      task: 'Maintenance',
      status: 'WALKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 51.2, y: 50 }],
    },
    robots: [
      {
        id: 'amr-01',
        name: 'AMR-01',
        type: 'Industrial AGV',
        position: { x: 50, y: 50 },
        currentSpeed: 1.5,
        maxSpeed: 2.0,
        direction: 0,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 50, y: 50 }, { x: 60, y: 50 }],
      }
    ],
    humans: [
      {
        id: 'human-01',
        name: 'Close Worker (H1)',
        position: { x: 51.2, y: 50 },
        currentSpeed: 1.0,
        expectedSpeed: 1.0,
        direction: Math.PI,
        task: 'Maintenance',
        status: 'WALKING',
        reactionTime: 0.5,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 51.2, y: 50 }],
      },
      {
        id: 'human-02',
        name: 'Medium Worker (H2)',
        position: { x: 50, y: 53.5 },
        currentSpeed: 0.8,
        expectedSpeed: 0.8,
        direction: 0,
        task: 'Inspection',
        status: 'WALKING',
        reactionTime: 0.5,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 50, y: 53.5 }],
      }
    ]
  },
  {
    id: 'multi-ec-05-inactive-agent',
    name: 'MULTI-EC-05: Inactive Agent Exclusion',
    description: 'An inactive AMR (isActive=false) parked in maintenance bay at close proximity to worker. Verifies inactive agent is excluded from active safety arbitration.',
    expectedOutcome: 'SAFE',
    duration: 10,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'Active AMR (R1)',
      type: 'Industrial AGV',
      position: { x: 10, y: 10 },
      currentSpeed: 1.0,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 10, y: 10 }, { x: 20, y: 10 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Worker (H1)',
      position: { x: 80, y: 80 },
      currentSpeed: 0.5,
      expectedSpeed: 0.5,
      direction: 0,
      task: 'Inspection',
      status: 'WORKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 80, y: 80 }],
    },
    robots: [
      {
        id: 'amr-01',
        name: 'Active AMR (R1)',
        type: 'Industrial AGV',
        position: { x: 10, y: 10 },
        currentSpeed: 1.0,
        maxSpeed: 2.0,
        direction: 0,
        status: 'MOVING',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 10, y: 10 }, { x: 20, y: 10 }],
      },
      {
        id: 'amr-02-inactive',
        name: 'Parked Inactive AMR (R2)',
        type: 'Industrial AGV',
        position: { x: 80.5, y: 80 },
        currentSpeed: 0,
        maxSpeed: 2.0,
        direction: 0,
        status: 'IDLE',
        stoppingTime: 0.8,
        baseRadius: 0.8,
        currentWaypointIndex: 0,
        isActive: false, // INACTIVE
        path: [{ x: 80.5, y: 80 }],
      }
    ],
    humans: [
      {
        id: 'human-01',
        name: 'Worker (H1)',
        position: { x: 80, y: 80 },
        currentSpeed: 0.5,
        expectedSpeed: 0.5,
        direction: 0,
        task: 'Inspection',
        status: 'WORKING',
        reactionTime: 0.5,
        currentWaypointIndex: 0,
        isActive: true,
        path: [{ x: 80, y: 80 }],
      }
    ]
  },
  {
    id: 'multi-ec-06-invalid-coords',
    name: 'MULTI-EC-06: Out-of-Bounds Coordinate Sanitization',
    description: 'Agent with out-of-range negative coordinates (-50, -50) evaluated alongside standard agents. Verifies coordinate distance clamping without crash.',
    expectedOutcome: 'SAFE',
    duration: 10,
    environment: { ...DEFAULT_ENVIRONMENT_CONFIG },
    safetyRules: { ...DEFAULT_SAFETY_RULES },
    initialRobot: {
      id: 'amr-01',
      name: 'AMR-01',
      type: 'Industrial AGV',
      position: { x: 10, y: 10 },
      currentSpeed: 1.0,
      maxSpeed: 2.0,
      direction: 0,
      status: 'MOVING',
      stoppingTime: 0.8,
      baseRadius: 0.8,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 10, y: 10 }, { x: 20, y: 10 }],
    },
    initialHuman: {
      id: 'human-01',
      name: 'Worker-01',
      position: { x: 90, y: 90 },
      currentSpeed: 0.5,
      expectedSpeed: 0.5,
      direction: 0,
      task: 'Inspection',
      status: 'WORKING',
      reactionTime: 0.5,
      currentWaypointIndex: 0,
      isActive: true,
      path: [{ x: 90, y: 90 }],
    },
  },
];
